# Generated by Django 3.2.7 on 2021-10-27 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TapGoApp', '0002_auto_20211026_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('online', 'online'), ('blocked', 'blocked')], default='pending', max_length=7),
        ),
        migrations.AlterField(
            model_name='healthreport',
            name='report',
            field=models.CharField(choices=[('Positive', 'Positive'), ('Unvaccinated', 'Unvaccinated'), ('Vaccinated', 'Vaccinated')], default='Not reported', max_length=12),
        ),
        migrations.AlterField(
            model_name='nationalid',
            name='id_num',
            field=models.SlugField(default='bb6579e4'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='typeUser',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Passenger', 'Passenger'), ('Driver', 'Driver'), ('Agent', 'Agent')], default='Passenger', max_length=9),
        ),
        migrations.AlterField(
            model_name='road',
            name='roadNum',
            field=models.CharField(choices=[('303', '303'), ('313', '313'), ('301', '301'), ('311', '311')], default='301', max_length=5),
        ),
    ]
