# Generated by Django 3.2.7 on 2021-10-27 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TapGoApp', '0003_auto_20211027_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='defaultUser.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='card',
            name='status',
            field=models.CharField(choices=[('blocked', 'blocked'), ('online', 'online'), ('pending', 'pending')], default='pending', max_length=7),
        ),
        migrations.AlterField(
            model_name='healthreport',
            name='report',
            field=models.CharField(choices=[('Unvaccinated', 'Unvaccinated'), ('Vaccinated', 'Vaccinated'), ('Positive', 'Positive')], default='Not reported', max_length=12),
        ),
        migrations.AlterField(
            model_name='nationalid',
            name='id_num',
            field=models.SlugField(default='af4b59de'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cardNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_account', to='TapGoApp.card'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='health',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_account', to='TapGoApp.healthreport'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='typeUser',
            field=models.CharField(choices=[('Agent', 'Agent'), ('Driver', 'Driver'), ('Admin', 'Admin'), ('Passenger', 'Passenger')], default='Passenger', max_length=9),
        ),
        migrations.AlterField(
            model_name='road',
            name='roadNum',
            field=models.CharField(choices=[('311', '311'), ('301', '301'), ('313', '313'), ('303', '303')], default='301', max_length=5),
        ),
    ]
