# Generated by Django 3.2.7 on 2021-10-27 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TapGoApp', '0004_auto_20211027_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('blocked', 'blocked'), ('online', 'online')], default='pending', max_length=7),
        ),
        migrations.AlterField(
            model_name='healthreport',
            name='report',
            field=models.CharField(choices=[('Vaccinated', 'Vaccinated'), ('Unvaccinated', 'Unvaccinated'), ('Positive', 'Positive')], default='Not reported', max_length=12),
        ),
        migrations.AlterField(
            model_name='nationalid',
            name='id_num',
            field=models.SlugField(default='1e09c5c4'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='images/defaultUser.png', upload_to='images/', verbose_name='Profile picture'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='typeUser',
            field=models.CharField(choices=[('Agent', 'Agent'), ('Admin', 'Admin'), ('Passenger', 'Passenger'), ('Driver', 'Driver')], default='Passenger', max_length=9),
        ),
        migrations.AlterField(
            model_name='road',
            name='roadNum',
            field=models.CharField(choices=[('301', '301'), ('311', '311'), ('313', '313'), ('303', '303')], default='301', max_length=5),
        ),
    ]
