# Generated by Django 3.2.7 on 2021-10-27 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TapGoApp', '0006_auto_20211027_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='affectStation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bus_station', to='TapGoApp.busstation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='status',
            field=models.CharField(choices=[('blocked', 'blocked'), ('online', 'online'), ('pending', 'pending')], default='pending', max_length=7),
        ),
        migrations.AlterField(
            model_name='nationalid',
            name='id_num',
            field=models.SlugField(default='4f6a35f5'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='typeUser',
            field=models.CharField(choices=[('Driver', 'Driver'), ('Passenger', 'Passenger'), ('Agent', 'Agent'), ('Admin', 'Admin')], default='Passenger', max_length=9),
        ),
        migrations.AlterField(
            model_name='road',
            name='roadNum',
            field=models.CharField(choices=[('303', '303'), ('311', '311'), ('301', '301'), ('313', '313')], default='301', max_length=5),
        ),
    ]
