# Generated by Django 3.2.7 on 2021-10-27 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TapGoApp', '0009_auto_20211027_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='cash',
            name='transaction',
            field=models.SlugField(default='e9ef5de4179a4'),
        ),
        migrations.AlterField(
            model_name='card',
            name='status',
            field=models.CharField(choices=[('blocked', 'blocked'), ('pending', 'pending'), ('online', 'online')], default='pending', max_length=7),
        ),
        migrations.AlterField(
            model_name='healthreport',
            name='report',
            field=models.CharField(choices=[('Vaccinated', 'Vaccinated'), ('Positive', 'Positive'), ('Unvaccinated', 'Unvaccinated')], default='Not reported', max_length=12),
        ),
        migrations.AlterField(
            model_name='nationalid',
            name='id_num',
            field=models.SlugField(default='855296ad'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='typeUser',
            field=models.CharField(choices=[('Passenger', 'Passenger'), ('Admin', 'Admin'), ('Driver', 'Driver'), ('Agent', 'Agent')], default='Passenger', max_length=9),
        ),
        migrations.AlterField(
            model_name='road',
            name='roadNum',
            field=models.CharField(choices=[('301', '301'), ('303', '303'), ('313', '313'), ('311', '311')], default='301', max_length=5),
        ),
    ]
