# Generated by Django 3.2.7 on 2021-10-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TapGoApp', '0010_auto_20211027_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='status',
            field=models.CharField(choices=[('online', 'online'), ('blocked', 'blocked'), ('pending', 'pending')], default='pending', max_length=7),
        ),
        migrations.AlterField(
            model_name='cash',
            name='transaction',
            field=models.SlugField(default='6b7c281db4504'),
        ),
        migrations.AlterField(
            model_name='healthreport',
            name='report',
            field=models.CharField(choices=[('Positive', 'Positive'), ('Vaccinated', 'Vaccinated'), ('Unvaccinated', 'Unvaccinated')], default='Not reported', max_length=12),
        ),
        migrations.AlterField(
            model_name='nationalid',
            name='id_num',
            field=models.SlugField(default='3fb45b77'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='typeUser',
            field=models.CharField(choices=[('Passenger', 'Passenger'), ('Driver', 'Driver'), ('Agent', 'Agent'), ('Admin', 'Admin')], default='Passenger', max_length=9),
        ),
        migrations.AlterField(
            model_name='road',
            name='roadNum',
            field=models.CharField(choices=[('311', '311'), ('301', '301'), ('313', '313'), ('303', '303')], default='301', max_length=5),
        ),
    ]
