# Generated by Django 3.2.7 on 2021-10-28 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TapGoApp', '0011_auto_20211028_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='status',
            field=models.CharField(choices=[('online', 'online'), ('pending', 'pending'), ('blocked', 'blocked')], default='pending', max_length=7),
        ),
        migrations.AlterField(
            model_name='cash',
            name='transaction',
            field=models.SlugField(default='79cb2023a7094'),
        ),
        migrations.AlterField(
            model_name='healthreport',
            name='report',
            field=models.CharField(choices=[('Vaccinated', 'Vaccinated'), ('Positive', 'Positive'), ('Unvaccinated', 'Unvaccinated')], default='Not reported', max_length=12),
        ),
        migrations.AlterField(
            model_name='nationalid',
            name='id_num',
            field=models.SlugField(default='0955db72'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='typeUser',
            field=models.CharField(choices=[('Passenger', 'Passenger'), ('Agent', 'Agent'), ('Admin', 'Admin'), ('Driver', 'Driver')], default='Passenger', max_length=9),
        ),
        migrations.AlterField(
            model_name='road',
            name='roadNum',
            field=models.CharField(choices=[('303', '303'), ('313', '313'), ('301', '301'), ('311', '311')], default='301', max_length=5),
        ),
    ]
