# Generated by Django 3.2.7 on 2021-11-08 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TapGoApp', '0012_auto_20211028_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='position',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='transaction',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='card',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('online', 'online'), ('blocked', 'blocked')], default='pending', max_length=7),
        ),
        migrations.AlterField(
            model_name='cash',
            name='transaction',
            field=models.SlugField(default='6374512b2f9c4'),
        ),
        migrations.AlterField(
            model_name='nationalid',
            name='id_num',
            field=models.SlugField(default='09c9d6a0'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='typeUser',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Passenger', 'Passenger'), ('Driver', 'Driver'), ('Agent', 'Agent')], default='Passenger', max_length=9),
        ),
        migrations.AlterField(
            model_name='road',
            name='roadNum',
            field=models.CharField(choices=[('301', '301'), ('303', '303'), ('311', '311'), ('313', '313')], default='301', max_length=5),
        ),
    ]
