# Generated by Django 3.2.7 on 2021-11-09 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TapGoApp', '0013_auto_20211108_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='sitAvailable',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bus',
            name='sitNum',
            field=models.IntegerField(default=40),
        ),
        migrations.AlterField(
            model_name='card',
            name='status',
            field=models.CharField(choices=[('online', 'online'), ('blocked', 'blocked'), ('pending', 'pending')], default='pending', max_length=7),
        ),
        migrations.AlterField(
            model_name='cash',
            name='transaction',
            field=models.SlugField(default='61747971a7404'),
        ),
        migrations.AlterField(
            model_name='healthreport',
            name='report',
            field=models.CharField(choices=[('Unvaccinated', 'Unvaccinated'), ('Positive', 'Positive'), ('Vaccinated', 'Vaccinated')], default='Not reported', max_length=12),
        ),
        migrations.AlterField(
            model_name='nationalid',
            name='id_num',
            field=models.SlugField(default='ab0bc0d6'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='typeUser',
            field=models.CharField(choices=[('Passenger', 'Passenger'), ('Driver', 'Driver'), ('Admin', 'Admin'), ('Agent', 'Agent')], default='Passenger', max_length=9),
        ),
        migrations.AlterField(
            model_name='road',
            name='roadNum',
            field=models.CharField(choices=[('303', '303'), ('313', '313'), ('311', '311'), ('301', '301')], default='301', max_length=5),
        ),
    ]
