# Generated by Django 3.2.7 on 2021-11-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TapGoApp', '0014_auto_20211109_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cash',
            name='transaction',
            field=models.SlugField(default='0c0b9e07d5ed4'),
        ),
        migrations.AlterField(
            model_name='nationalid',
            name='id_num',
            field=models.SlugField(default='2c5e2b80'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='typeUser',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Driver', 'Driver'), ('Passenger', 'Passenger'), ('Agent', 'Agent')], default='Passenger', max_length=9),
        ),
        migrations.AlterField(
            model_name='road',
            name='roadNum',
            field=models.CharField(choices=[('311', '311'), ('303', '303'), ('301', '301'), ('313', '313')], default='301', max_length=5),
        ),
    ]
