# Generated by Django 3.2.7 on 2021-11-09 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TapGoApp', '0015_auto_20211109_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('online', 'online'), ('blocked', 'blocked')], default='pending', max_length=7),
        ),
        migrations.AlterField(
            model_name='cash',
            name='transaction',
            field=models.SlugField(default='32634c17e5144'),
        ),
        migrations.AlterField(
            model_name='healthreport',
            name='report',
            field=models.CharField(choices=[('Vaccinated', 'Vaccinated'), ('Unvaccinated', 'Unvaccinated'), ('Positive', 'Positive')], default='Not reported', max_length=12),
        ),
        migrations.AlterField(
            model_name='nationalid',
            name='id_num',
            field=models.SlugField(default='d48043d1'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='typeUser',
            field=models.CharField(choices=[('Agent', 'Agent'), ('Driver', 'Driver'), ('Admin', 'Admin'), ('Passenger', 'Passenger')], default='Passenger', max_length=9),
        ),
        migrations.AlterField(
            model_name='road',
            name='roadNum',
            field=models.CharField(choices=[('301', '301'), ('313', '313'), ('303', '303'), ('311', '311')], default='301', max_length=5),
        ),
    ]
